/** Declaration file generated by dts-gen */

export class MenuIcon {
    constructor(props: any, context: any, updater: any);
    render(): any;
    static displayName: string;
}
export class SideNav {
    constructor(props: any, context: any, updater: any);
    componentWillReceiveProps(nextProps: any): void;
    getDefaultContent(): any;
    getInitialState(): any;
    getStyle(): any;
    hideNav(): void;
    onTouchEnd(evt: any): void;
    onTouchMove(evt: any): void;
    onTouchStart(evt: any): void;
    render(): any;
    shouldComponentUpdate(nextProps: any, nextStates: any): any;
    showNav(): void;
    update(): void;
    static displayName: string;
}
export namespace SideNav {
    namespace propTypes {
        function children(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function itemHoverStyle(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function itemStyle(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function items(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function navStyle(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onHideNav(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function onShowNav(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function showNav(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function style(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function title(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        function titleStyle(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        namespace children {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace itemHoverStyle {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace itemStyle {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace items {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace navStyle {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onHideNav {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace onShowNav {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace showNav {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace style {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace title {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
        namespace titleStyle {
            function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
        }
    }
}
